name: Targets  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /targets get lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-g.zip targets/get/index.js node_modules
      - name: target get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-g
            zip_file: m-s-targets-g.zip
      - name: /targets post lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-po.zip targets/post/index.js node_modules
      - name: target get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-po
            zip_file: m-s-targets-po.zip
      - name: /targets/{target_id} get lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-target-g.zip targets/target_id/get/index.js node_modules
      - name: target get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-target-g
            zip_file: m-s-targets-target-g.zip
      - name: /targets/{target_id} put lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-target-pu.zip targets/target_id/put/index.js node_modules
      - name: target get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-target-pu
            zip_file: m-s-targets-target-pu.zip
      - name: /targets/{target_id} delete lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-target-d.zip targets/target_id/delete/index.js node_modules
      - name: target get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-target-d
            zip_file: m-s-targets-target-d.zip          
      - name: /targets/{target_id}/tags get lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-target-tags-g.zip targets/target_id/tags/get/index.js node_modules
      - name: targets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-target-tags-g
            zip_file: m-s-targets-target-tags-g.zip
      - name: /targets/{target_id}/tags post lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targets-target-tags-po.zip targets/target_id/tags/post/index.js node_modules
      - name: targets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targets-target-tags-po
            zip_file: m-s-targets-target-tags-po.zip
      - name: /targets/bookmarklet get lambda deploy zip
        uses: algorotoscope/targets@main
        with:
            args: zip -qq -r m-s-targetsbookmarklet-g.zip targets/bookmarklet/get/index.js node_modules
      - name: targets get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-targetsbookmarklet-g
            zip_file: m-s-targetsbookmarklet-g.zip  
                      